name: coverage
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: report.json
          base-coverage-file: report.json
          github-token: ${{ secrets.SECRET_TOKEN }}
