name: coverage-pr-report
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  coverage-pr-report:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ArtiomTr/jest-coverage-report-action@262a7bb0b20c4d1d6b6b026af0f008f78da72788 # v2.3.1
        with:
          test-script: npm run test:coverage
